<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tennis_weather_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.tennis_weather':
      //TODO write help page content
      //(see Drupal\loremipsum\loremipsum.module for reference)
      return t('<h2>[TITLE]</h2><p>[CONTENT]');
  }
}

/**
 * Implements hook_theme().
 */
function tennis_weather_theme($existing, $type, $theme, $path) {
  $variables = array(
    'tennis_weather' => array(
      'variables' => array( 'subheading' => NULL,
                            'summary' => NULL,
                            'database_test' => NULL,
                            'current_cond' => NULL,
                            'timestamp' => NULL,
                            'forecast' => NULL,
                            'current_icon' => NULL,
                            'debug_info' => NULL,
                            'radar_gif' => NULL,
                            'map_img' => NULL),
      'template' => 'tennis_weather',
    ),
  );
  return $variables;
}


/**
 * Template preprocess function for Tennis Weather Checker.
 * Dynamically change formatting (color, emphasis, etc.) of forecast info.
 * @param variables
 *   An associative array containing:
 *   - forecast
 */
function template_preprocess_tennis_weather(&$variables) {
  foreach ($variables['forecast'] as &$hourForecast) {
    // TODO: use SafeMarkup?

    // Convert 24 hour to 12 hour AM/PM
    if ($hourForecast->FCTTIME->hour == 0 || $hourForecast->FCTTIME->hour == 12) {
      $hourForecast->FCTTIME->hour = 12;
    }
    else if ($hourForecast->FCTTIME->hour > 12) {
      $hourForecast->FCTTIME->hour = $hourForecast->FCTTIME->hour - 12;
    }

    $temp = $hourForecast->temp->english; // max length: 3
    $tempUnitsF = ' &deg;F';
    $tempUnitsC = ' &deg;C';
    $wind = $hourForecast->wspd->english; // max length: 3
    $windUnitsMPH = ' mph';
    $precip = $hourForecast->pop . ' %'; // max length: 5

    $paddedTime = sprintf("%'_-2s %s ", $hourForecast->FCTTIME->hour, $hourForecast->FCTTIME->ampm);
    $paddedTime = str_replace("_", "&nbsp;", $paddedTime);

    $paddedTemp = sprintf("Temperature: %'_3s %s", $temp, $tempUnitsF);
    $paddedTemp = str_replace("_", "&nbsp;", $paddedTemp);

    $paddedWind = sprintf("Wind: %'_3s %s", $wind, $windUnitsMPH);
    $paddedWind = str_replace("_", "&nbsp;", $paddedWind);

    $paddedPrecip = sprintf("Chance of precipitation: %'_5s", $precip);
    $paddedPrecip = str_replace("_", "&nbsp;", $paddedPrecip);

    $formattedTime = $paddedTime;
    $formattedTemp = $paddedTemp;
    $formattedWind = $paddedWind;
    $formattedPrecip = $paddedPrecip;

    // Change color of time text depending on weather conditions
    // TODO: make these conditions configurable
    if ($hourForecast->temp->english >= 94 || $hourForecast->wspd->english >= 18 || $hourForecast->pop >= 40) {
      $formattedTime = "<font color=red><b>" . $paddedTime . "</b></font>";
    }
    else if ($hourForecast->temp->english >= 90 || $hourForecast->wspd->english >= 12 || $hourForecast->pop >= 30) {
      $formattedTime = "<font color=orange><b>" . $paddedTime . "</b></font>";
    }
    else {
      $formattedTime = "<font color=green><b>" . $paddedTime . "</b></font>";
    }

    /**
    * Bold problematic part(s) of forecast
    **/
    // Check temperature
    if ($hourForecast->temp->english >= 90) {
      $formattedTemp = "<b>". $paddedTemp ."</b>";
    }
    // Check windspeed
    if ($hourForecast->wspd->english >= 12) {
      $formattedWind = "<b>". $paddedWind ."</b>";
    }
    // Check precipitation probability
    if ($hourForecast->pop >= 30) {
      $formattedPrecip = "<b>". $paddedPrecip ."</b>";
    }

    $hourForecast = $formattedTime . $formattedTemp . '&emsp;&emsp;&emsp;' . $formattedWind . '&emsp;&emsp;&emsp;' . $formattedPrecip;
  }

  // Conditional formatting of forecast summary text
  // TODO: make these criteria configurable
  if ($variables['summary']['today']['value'] > 1){
    $variables['summary']['today'] = '<font color=orange><b>'. sprintf($variables['summary']['today']['string'], $variables['summary']['today']['value']) . '</b></font>';
  }
  else {
    $variables['summary']['today'] = sprintf($variables['summary']['today']['string'], $variables['summary']['today']['value']);
  }

  if ($variables['summary']['hr']['value'] > 1){
    $variables['summary']['hr'] = '<font color=red><b>'. sprintf($variables['summary']['hr']['string'], $variables['summary']['hr']['value']) . '</b></font>';
  }
  else if ($variables['summary']['hr']['value'] > .1) {
    $variables['summary']['hr'] = '<font color=orange><b>'. sprintf($variables['summary']['hr']['string'], $variables['summary']['hr']['value']) . '</b></font>';
  }
  else {
    $variables['summary']['hr'] = sprintf($variables['summary']['hr']['string'], $variables['summary']['hr']['value']);
  }
}
